### ISSUE TITLE
Is there a way to prof?

### ISSUE THREAD

**Issue by ghost** [capnproto/node-capnp#29]
I run prof as: https://nodejs.org/en/docs/guides/simple-profiling/.
But I found this cann't prof shared library.
Is there a way to prof shared library (nodejs native module) ?

**Comment by kentonv** [comment]
Sorry, I'm afraid I don't know.

**Comment by ghost** [comment]
Thank you, @kentonv. I'll try some tools like google's gperftools to do the prof. (Just see nodejs is a C++ problem)
