### ISSUE TITLE
Can't install from npm (0.1.11)

### ISSUE THREAD

**Issue by ptusch** [capnproto/node-capnp#35]
Good day everyone,

I tried to install this package from npm.
To be explicit, it was version `0.1.11`.

## Versions
* node: 4.4.7
* npm: 2.15.8
* node-gyp: 3.6.2
* python: 2.7.9

Turns out it can not compile nicely - there seems to be some kind of linking error (can't find the library).

I installed capnproto from the website using the tarball (0.6.1) and compiled it from source.
The contents are then installed to `/usr/local/` (specifying the prefix doesn't help either - then I run into different issues but that would be another issue all together).

The [installation log](https://github.com/capnproto/node-capnp/files/1306460/capnp__0_1_11__install.txt) is attached. I hope it is helpful.

After some investigation, it seems like the `node4` branch works nicely. Unfortunately, the npm version on npmjs.com still points to the old master.
I suspect this is all fixed when `node4` is merged back to `master` but I'm not sure how the strategy is for that task.

I hope this is any helpful.

**Comment by ptusch** [comment]
Oopsie, I just found another issue (#28) that actually explains the situation nicely.
Sorry to bother you.

**Comment by kentonv** [comment]
Hi @ptusch,

Actually, thanks for filing this, because you reminded me that this can actually be published now that Cap'n Proto 0.6 is released. I've published version 0.2.0 which is tested and works on node 4 and 6.
