### ISSUE TITLE
Doesn't build against latest sandstorm (LowLevelAsyncIoProvider changed interface)

### ISSUE THREAD

**Issue by dmitry-sher** [capnproto/node-capnp#36]
When I download latest sandstorm (commit #b05c931907787325c30424fb4376fa7a8d66ab8b) and run make in sandstorm, it downloads node-capnp sources, which depend on KJ project. The class `capnp.cc:576:class UvLowLevelAsyncIoProvider final: public kj::LowLevelAsyncIoProvider` is out of sync with latest `async-io.h:507:LowLevelAsyncIoProvider`. In my sandstorm build these are files `deps/node-capnp/src/node-capnp/capnp.cc` and `deps/capnproto/c++/ekam-provider/c++ header/kj/async-io.h`. 

The differences are:
```
  virtual Own<ConnectionReceiver> wrapListenSocketFd(Fd fd, NetworkFilter& filter, uint flags = 0) = 0;
  virtual Own<DatagramPort> wrapDatagramSocketFd(Fd fd, NetworkFilter& filter, uint flags = 0);
```

First method has changed signature in recent `async-io.h` (network filter added), the second one is not implemented in `capnp.cc`.

I've managed to build it, adding this code, but still checking if it's working:
```
  kj::Own<kj::ConnectionReceiver> wrapListenSocketFd(Fd fd, NetworkFilter& filter, uint flags = 0) override {
    return kj::heap<UvConnectionReceiver>(eventPort.getUvLoop(), fd, flags);
  }

  kj::Own<kj::DatagramPort> wrapDatagramSocketFd(Fd fd, NetworkFilter& filter, uint flags = 0) override {
    // TODO(soon):  Implement this.
    KJ_FAIL_ASSERT("wrapDatagramSocketFd not implemented.");
  }
```

**Comment by kentonv** [comment]
Whoops, I had these changes sitting in my local copy but failed to upload them. I guess I forgot that node-capnp is a separate repo from capnproto itself. Sorry about that. Fixed now.
