### ISSUE TITLE
13 MB `capnp-samples` folder published on npm for version 0.3.0

### ISSUE THREAD

**Issue by lmammino** [capnproto/node-capnp#40]
You probably published by mistake the folder `capnp-samples` when running `npm publish` manually.

This folder is relatively big (**13MB**) and this might be an issue in environments where disk space is a problem (e.g. AWS lambda or raspberry pi).

Check here the current content of the package: https://unpkg.com/capnp@0.3.0/

And compare the screenshot here from my current installation

<img width="553" alt="screen shot 2018-02-09 at 3 04 40 pm" src="https://user-images.githubusercontent.com/205629/36035492-fbcabea2-0dae-11e8-8908-3fdf0db4a4ee.png">

Can you please publish a new version that doesn't include the `capnp-samples` folder?

Thanks

CC: @dkatavic who actually spotted this issue and might be interested as well in a resolution

**Comment by kentonv** [comment]
Wow, npm just bundles up and publishes the entire folder recursively?

I mean I guess in retrospect I don't know what else it could do but that's kind of terrifying TBH.

OK I've published 0.3.1 which hopefully doesn't contain any random scratch stuff I was playing with... Sorry about that.

**Comment by lmammino** [comment]
Yeah, it's a bit dangerous as a default behaviour, especially because you might have in your source folder sensible files which shouldn't be published...

A good practice is to whitelist all the files that you want to publish in the `package.json`:

For example:

```json
{
  "files": [
     "src/*"
  ]
}
```

This way you can also exclude tests, documentation, examples or other files that might be heavy and not important when using the lib as a dependency in production.

More info [here](https://docs.npmjs.com/files/package.json#files).

Anyway, thank you for being so quick in addressing the issue 👍
