### ISSUE TITLE
Is the NPM registry for this out of date?

### ISSUE THREAD

**Issue by Michael-S** [capnproto/node-capnp#49]
This question could be full of fundamental misunderstandings, and if it is then I apologize for wasting your time.  But when I go to https://registry.npmjs.org/capnp  the "time" section lists "0.4.0" as the latest version but further down the "versions" section doesn't have it.  I'm hitting build errors because my npm builds can't find version 0.4.0, and my (wild) guess is that the discrepancy is the cause.

Thoughts?

**Comment by kentonv** [comment]
See https://github.com/capnproto/node-capnp/issues/41#issuecomment-452095765 -- I had briefly published 0.4.0 but found that the published version didn't work (even though the local version did), so had to un-publish. I haven't yet had a chance to debug. Would welcome help from a node/npm expert.
