### ISSUE TITLE
Node 12 support

### ISSUE THREAD

**Issue by deepakprabhakara** [capnproto/node-capnp#52]
Lots of changes in Node12 v8 and nan which breaks this lib. I have a fix here - https://github.com/redsift/node-capnp/tree/node12 but it's currently untested (although local tests do pass). I will submit a PR once tested.

**Comment by rezamt** [comment]
Hi Deepak
I checkout your branch - node12 -, installed node v12.0.0 - on ubuntu 18 and also installed make, g++ and capnp v7.

Build was successful but when I am trying to execute the capnp.node I am getting the following error:
```
reza@reza-virtual-machine:~/node-capnp/bin/linux-x64-v8-7.4$ ./capnp.node 
Segmentation fault (core dumped)

```

I really need this for my project. Are you able to help me ? is there anything I am missing here?

Here is my build environment:

```bash
reza@reza-virtual-machine:~/node-capnp/bin/linux-x64-v8-7.4$ capnp --version
Cap'n Proto version 0.7.0

reza@reza-virtual-machine:~/node-capnp/bin/linux-x64-v8-7.4$ make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu

reza@reza-virtual-machine:~/node-capnp/bin/linux-x64-v8-7.4$ g++ --version
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

reza@reza-virtual-machine:~/node-capnp/bin/linux-x64-v8-7.4$ node --version
v12.0.0

reza@reza-virtual-machine:~/node-capnp/bin/linux-x64-v8-7.4$ npm --version
6.9.0

```


Also tried node10 branch and once the build is completed still the binary shows me the same error above.

Thanks
Rez

**Comment by kentonv** [comment]
@deepakprabhakara FWIW your changes look good to me. I look forward to the PR.

@rezamt `capnp.node` is not a program, it's a node module. You have to import it from JavaScript in node, not run it.

**Comment by rezamt** [comment]
@kentonv  thanks for your help. As you said I was wrong - it's working for me. so no issue.

**Comment by deepakprabhakara** [comment]
Late on this but glad your issue is sorted @rezamt. @kentonv Excellent, I'll submit the PR. There are still lots of warnings which I did not address since I wanted to get it working first. We are using it without any issues so far though. I don't have any good suggestion yet on how we could potentially combine this with node10 in the same code base, is it possible to use macros?

**Comment by kentonv** [comment]
Hi @deepakprabhakara,

Historically I have created a new branch each time there was a major Node update. This probably isn't really the right way to do it, but I can't really ask you to go out of your way to improve our versioning approach, so I'm happy with creating yet another branch for node12...

**Comment by deepakprabhakara** [comment]
PR submitted here - https://github.com/capnproto/node-capnp/pull/57

**Comment by ocdtrekkie** [comment]
This issue can be closed.
