### ISSUE TITLE
Document how exceptions work.

### ISSUE THREAD

**Issue by zenhack** [capnproto/node-capnp#53]
Nothing in the README discusses how capnproto exceptions work with this library. I figured bits of this out by reading usage in the Sandstorm codebase and the source code itself, but ideally that wouldn't be necessary. I was trying to figure out how to throw an `unimplemented` exception specifically, and I *think* this does it:

https://github.com/sandstorm-io/sandstorm/pull/3172/commits/d968a8024903b615f298c1c640167c2382a2ab86

...but I'm not 100% sure that's how this is supposed to work, and there's no docs.

**Comment by kentonv** [comment]
Yep, that's how it works... `kjType` is a string specifying the lower-cased name of the `kj::Exception::Type` enum value. Happy to accept a PR documenting this.
