### ISSUE TITLE
Getting Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by rezamt** [capnproto/node-capnp#54]
Hi everyone

Tried to build from git repo on `ubuntu 19 `- the build is successfully despite some warning (log is referenced down below)

```
reza@ubu1901:~/node-capnp/bin/linux-x64-v8-6.8$ ls -rtl
total 672
-rwxr-xr-x 1 reza reza 684888 Jan  3 23:55 capnp.node

```

when I am calling it:

```
reza@ubu1901:~/node-capnp/bin/linux-x64-v8-6.8$ ./capnp.node 
Segmentation fault (core dumped)

```

### Build Environment
```
reza@ubu1901:~$ uname -a
Linux ubu1901 5.0.0-36-generic #39-Ubuntu SMP Tue Nov 12 09:46:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

reza@ubu1901:~$ node --version
v10.18.0

reza@ubu1901:~$ npm --version
6.13.4

reza@ubu1901:~$ g++ --version
g++ (Ubuntu 8.3.0-6ubuntu1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

reza@ubu1901:~$ make --version
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

```

### Reference to my npm build log
[log here](https://gist.github.com/rezamt/6276a1682c368390d8d7bab07ed191f0)

------

I have also tried to go with `npm install capnp`  but it wasn't successful and it failed.

I am sure that I have installed the `capnp C++ `successfully (as instructed)

Log can be inspected [here](https://gist.github.com/rezamt/cc3da7d0885aa31a0e46660e86a055ac)

```
reza@ubu1901:~/capnproto-c++-0.7.0$ which capnp
/usr/local/bin/capnp

reza@ubu1901:~/capnproto-c++-0.7.0$ capnp --version
Cap'n Proto version 0.7.0
```

Also tried different version of nodes but still the same it doesn't compile on node 10.x.x above and it fails on my mac osx , so decided to go with ubuntu.

Thanks for your help in advance
Rez

**Comment by kentonv** [comment]
`capnp.node` is not a program. It is a Node extension. It is not meant to be executed on the command line. You need to install the capnp npm module and then import it from a node program.

> I have also tried to go with npm install capnp but it wasn't successful and it failed.

In what way did it fail? The log you provided doesn't seem to show the failure.

**Comment by rezamt** [comment]
Hi @kentonv 
thanks a lot for ur help. I was wrong, so I did as you said and it's working fine. 

I was doing it in go, thats why I thought it should be an executable ! 

Again thank you and please close this.

Reza
